CREATE DATABASE web_sites DEFAULT CHARACTER SET 'utf8';

USE web_sites;

CREATE TABLE sites (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  ecrypt_parr VARCHAR(255) NOT NULL,
  domain VARCHAR(255) NOT NULL,
  name_db VARCHAR(100) NOT NULL,
) ENGINE = InnoDB;