#! /usr/bin/python3

import cgi
import pwd
from hashlib import sha256


def verify_user(username: str) -> bool:
    try:
        pwd.getpwnam(username)
        return True
    except KeyError:
        return False


def verify_password(password: str) -> bool:
    with open('credential', 'r') as cred:
        return cred.read() == sha256(password.encode('utf-8')).hexdigest()
    